 const countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Australia",
   " Germany",
    "France",
    "Italy",
    "Spain",
    "Mexico",
    "Brazil",
    "China",
    "Japan",
    "South Korea",
    "India",
    "Russia",
    "Turkey",
    "Saudi Arabia",
    "United Arab Emirates",
    "South Africa",
    "Nigeria",
    "Egypt",
    "Kenya",
    "Argentina",
    "Colombia",
    "Chile",
];
export default countries;